import React, { useState } from "react";
import "./App.css";

// Combined list of 190 motivational and inspirational quotes with known authors
const quotes = [
  { quote: "The life of man is of no greater duration than the breath of his nostrils.", author: "Plato" },
  { quote: "You cannot find peace by avoiding life.", author: "Virginia Woolf" },
  { quote: "The strongest principle of growth lies in the human choice.", author: "George Eliot" },
  { quote: "We have to continually be jumping off cliffs and developing our wings on the way down.", author: "Kurt Vonnegut" },
  { quote: "Amateurs sit and wait for inspiration, the rest of us just get up and go to work.", author: "Stephen King" },
  { quote: "Get it down. Take chances. It may be bad, but it's the only way you can do anything really good.", author: "William Faulkner" },
  { quote: "As a writer, you should not judge, you should understand.", author: "Ernest Hemingway" },
  { quote: "To produce a mighty book, you must choose a mighty theme.", author: "Herman Melville" },
  { quote: "There is nothing noble in being superior to your fellow man; true nobility is being superior to your former self.", author: "Ernest Hemingway" },
  { quote: "I was never afraid of failure; for I would sooner fail than not be among the greatest.", author: "John Keats" },
  { quote: "If you have built castles in the air, your work need not be lost; that is where they should be. Now put the foundations under them.", author: "Henry David Thoreau" },
  { quote: "There is no such thing as race. None. There is just a human race—scientifically, anthropologically.", author: "Toni Morrison" },
  { quote: "Not everything that is faced can be changed, but nothing can be changed until it is faced.", author: "James Baldwin" },
  { quote: "No one is born hating another person because of the color of his skin, or his background, or his religion.", author: "Nelson Mandela" },
  { quote: "An unexamined life is not worth living.", author: "Socrates" },
  { quote: "Life is trying things to see if they work.", author: "Ray Bradbury" },
  { quote: "You only live once, but if you do it right, once is enough.", author: "Mae West" },
  { quote: "Get busy living or get busy dying.", author: "Stephen King" },
  { quote: "It is better to fail in originality than to succeed in imitation.", author: "Herman Melville" },
  { quote: "Nothing in the world can take the place of persistence.", author: "Calvin Coolidge" },
  { quote: "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.", author: "Ralph Waldo Emerson" },
  { quote: "The only thing we have to fear is fear itself.", author: "Franklin D. Roosevelt" },
  { quote: "To be, or not to be, that is the question.", author: "William Shakespeare" },
  { quote: "That which does not kill us makes us stronger.", author: "Friedrich Nietzsche" },
  { quote: "It is better to have loved and lost than never to have loved at all.", author: "Alfred Tennyson" },
  { quote: "Ask not what your country can do for you, ask what you can do for your country.", author: "John F. Kennedy" },
  { quote: "A small leak will sink a great ship.", author: "Benjamin Franklin" },
  { quote: "In the middle of every difficulty lies opportunity.", author: "Albert Einstein" },
  { quote: "Life isn’t about finding yourself. Life is about creating yourself.", author: "George Bernard Shaw" },
  { quote: "The good news is you're the pilot.", author: "Michael Altshuler" },
  { quote: "I can't change the direction of the wind, but I can adjust my sails to always reach my destination.", author: "Jimmy Dean" },
  { quote: "It is often the small steps, not the giant leaps, that bring about the most lasting change.", author: "Queen Elizabeth II" },
  { quote: "In the long run, you make your own luck—good, bad, or indifferent.", author: "Loretta Lynn" },
  { quote: "Never limit yourself because of others’ limited imagination; never limit others because of your own limited imagination.", author: "Mae Jemison" },
  { quote: "When you have a dream, you've got to grab it and never let go.", author: "Carol Burnett" },
  { quote: "Let us make our future now, and let us make our dreams tomorrow's reality.", author: "Malala Yousafzai" },
  { quote: "All dreams are within reach. All you have to do is keep moving towards them.", author: "Viola Davis" },
  { quote: "Dreams don’t have to just be dreams. You can make it a reality; if you just keep pushing and keep trying, then eventually you’ll reach your goal.", author: "Naomi Osaka" },
  { quote: "Shoot for the moon. Even if you miss, you'll land among the stars.", author: "Norman Vincent Peale" },
  { quote: "I try to create sympathy for my characters, then turn the monsters loose.", author: "Stephen King" },
  { quote: "If you can tell stories, create characters, devise incidents, and have sincerity and passion, it doesn't matter a damn how you write.", author: "Somerset Maugham" },
  { quote: "It took me fifteen years to discover I had no talent for writing, but I couldn't give it up because by that time I was too famous.", author: "Robert Benchley" },
  { quote: "Any man who keeps working is not a failure.", author: "Ray Bradbury" },
  { quote: "If you have other things in your life—family, friends, good productive day work—these can interact with your writing and the sum will be all the richer.", author: "David Brin" },
  { quote: "Almost anyone can be an author; the business is to collect money and fame from this state of being.", author: "A.A. Milne" },
  { quote: "Only in men's imagination does every truth find an effective and undeniable existence.", author: "Joseph Conrad" },
  { quote: "Anecdotes don't make good stories. Generally I dig down underneath them so far that the story that finally comes out is not what people thought their anecdotes were about.", author: "Alice Munro" },
  { quote: "You learn by writing short stories. Keep writing short stories. The money's in novels, but writing short stories keeps your writing lean and pointed.", author: "Larry Niven" },
  { quote: "Everywhere I go I'm asked if I think the university stifles writers. My opinion is that they don't stifle enough of them.", author: "Flannery O'Connor" },
  { quote: "There's no such thing as writer's block. That was invented by people in California who couldn't write.", author: "Terry Pratchett" },
  { quote: "No one can write decently who is distrustful of the reader's intelligence or whose attitude is patronizing.", author: "E.B. White" },
  { quote: "Rejection slips, or form letters, however tactfully phrased, are lacerations of the soul, if not quite inventions of the devil—but there is no way around them.", author: "Isaac Asimov" },
  { quote: "In general…there's no point in writing hopeless novels. We all know we're going to die; what's important is the kind of men and women we are in the face of this.", author: "Anne Lamott" },
  { quote: "Tell the readers a story! Because without a story, you are merely using words to prove you can string them together in logical sentences.", author: "Anne McCaffrey" },
  { quote: "Imagination is like a muscle. I found out that the more I wrote, the bigger it got.", author: "Philip José Farmer" },
  { quote: "Ideas are like rabbits. You get a couple and learn how to handle them, and pretty soon you have a dozen.", author: "John Steinbeck" },
  { quote: "Put down everything that comes into your head and then you’re a writer. But an author is one who can judge his own stuff’s worth, without pity, and destroy most of it.", author: "Colette" },
  { quote: "Sooner or later every writer evolves his own definition of a story. A reflection of life plus beginning and end (life seems not to have either) and a meaning.", author: "Graham Greene" },
  { quote: "A good story is a dream shared by the author and the reader.", author: "Victor Hugo" },
  { quote: "Start writing, no matter what. The water does not flow until the faucet is turned on.", author: "Louis L’Amour" },
  { quote: "If there's a book that you want to read, but it hasn't been written yet, then you must write it.", author: "Toni Morrison" },
  { quote: "I'm writing a first draft and reminding myself that I'm simply shoveling sand into a box so that later I can build castles.", author: "Shannon Hale" },
  { quote: "The more closely the author thinks of why he wrote, the more he comes to regard his imagination as a kind of self-generating cement which glued his facts together.", author: "Norman Mailer" },
  { quote: "Writing is not necessarily something to be ashamed of, but do it in private and wash your hands afterwards.", author: "Robert A. Heinlein" },
  { quote: "A book is made from a tree. It is an assemblage of flat, flexible parts imprinted with dark pigmented squiggles.", author: "Carl Sagan" },
  { quote: "Words do not express thoughts very well. They always become a little different immediately after they are expressed.", author: "Hermann Hesse" },
  { quote: "Writing books is the closest men ever come to childbearing.", author: "Norman Mailer" },
  { quote: "Find out the reason that commands you to write; see whether it has spread its roots into the very depth of your heart.", author: "Rainer Maria Rilke" },
  { quote: "You never really understand a person until you consider things from his point of view.", author: "Harper Lee" },
  { quote: "The purpose of a writer is to keep civilization from destroying itself.", author: "Albert Camus" },
  { quote: "You don’t start out writing good stuff. You start out writing crap and thinking it’s good stuff, and then gradually you get better at it.", author: "Octavia E. Butler" },
  { quote: "The scariest moment is always just before you start.", author: "Stephen King" },
  { quote: "You can’t wait for inspiration. You have to go after it with a club.", author: "Jack London" },
  { quote: "The first draft is just you telling yourself the story.", author: "Terry Pratchett" },
  { quote: "There is no greater agony than bearing an untold story inside you.", author: "Maya Angelou" },
  { quote: "To the well-organized mind, death is but the next great adventure.", author: "J.K. Rowling" },
  { quote: "You have brains in your head. You have feet in your shoes. You can steer yourself any direction you choose.", author: "Dr. Seuss" },
  { quote: "If you want to know what a man's like, take a good look at how he treats his inferiors, not his equals.", author: "J.K. Rowling" },
  { quote: "We are all in the gutter, but some of us are looking at the stars.", author: "Oscar Wilde" },
  { quote: "Fairy tales are more than true: not because they tell us that dragons exist, but because they tell us that dragons can be beaten.", author: "Neil Gaiman" },
  { quote: "The opposite of love is not hate, it's indifference.", author: "Elie Wiesel" },
  { quote: "It is impossible to live without failing at something, unless you live so cautiously you might as well not have lived at all.", author: "J.K. Rowling" },
  { quote: "A little nonsense now and then, is cherished by the wisest man.", author: "Roald Dahl" },
  { quote: "Just don’t give up trying to do what you really want to do. Where there is love and inspiration, I don’t think you can go wrong.", author: "Ella Fitzgerald" },
  { quote: "Forever is composed of nows.", author: "Emily Dickinson" },
  { quote: "So many things are possible just as long as you don’t know they’re impossible.", author: "Norton Juster" },
  { quote: "It’s the possibility of having a dream come true that makes life interesting.", author: "Paulo Coelho" },
  { quote: "Your vision will become clear only when you can look into your own heart.", author: "Carl Jung" },
  { quote: "The person who makes a success of living is the one who sees his goal steadily and aims for it unswervingly.", author: "Cecil B. DeMille" },
  { quote: "Do not go where the path may lead; go instead where there is no path and leave a trail.", author: "Ralph Waldo Emerson" },
  { quote: "You know you're in love when you can't fall asleep because reality is finally better than your dreams.", author: "Dr. Seuss" },
  { quote: "I am so clever that sometimes I don't understand a single word of what I am saying.", author: "Oscar Wilde" },
  { quote: "Be yourself; everyone else is already taken.", author: "Oscar Wilde" },
  { quote: "Two things are infinite: the universe and human stupidity; and I'm not sure about the universe.", author: "Albert Einstein" },
  { quote: "Imperfection is beauty, madness is genius and it's better to be absolutely ridiculous than absolutely boring.", author: "Marilyn Monroe" },
  { quote: "Yesterday is history, tomorrow is a mystery, today is a gift of God, which is why we call it the present.", author: "Bill Keane" },
  { quote: "Don’t walk in front of me… I may not follow. Don’t walk behind me… I may not lead. Walk beside me… just be my friend.", author: "Albert Camus" },
  { quote: "This life is what you make it. No matter what, you're going to mess up sometimes, it's a universal truth.", author: "Marilyn Monroe" },
  { quote: "So, this is my life. And I want you to know that I am both happy and sad and I'm still trying to figure out how that could be.", author: "Stephen Chbosky" },
  { quote: "Many of life's failures are people who did not realize how close they were to success when they gave up.", author: "Thomas Edison" },
  { quote: "The secret of success is to do the common thing uncommonly well.", author: "John D. Rockefeller" },
  { quote: "Don't be distracted by criticism. Remember—the only taste of success some people get is to take a bite out of you.", author: "Zig Ziglar" },
  { quote: "There are two ways you can get through the pain. You can let it destroy you, or you can use it as fuel to drive you: to dream bigger, work harder.", author: "Taylor Swift" },
  { quote: "Luck? I don't know anything about luck. I've never banked on it and I'm afraid of people who do.", author: "Lucille Ball" },
  { quote: "In the end, it's not the years in your life that count. It's the life in your years.", author: "Abraham Lincoln" },
  { quote: "Life is a succession of lessons which must be lived to be understood.", author: "Ralph Waldo Emerson" },
  { quote: "Never let the fear of striking out keep you from playing the game.", author: "Babe Ruth" },
  { quote: "If life were predictable, it would cease to be life and be without flavor.", author: "Eleanor Roosevelt" },
  { quote: "Whatever you can do, or dream you can, begin it. Boldness has genius, power and magic in it.", author: "Johann Wolfgang von Goethe" },
  { quote: "People often say that motivation doesn’t last. Well, neither does bathing.", author: "Zig Ziglar" },
  { quote: "I attribute my success to this: I never gave or took any excuse.", author: "Florence Nightingale" },
  { quote: "Two roads diverged in a wood, and I—I took the one less traveled by, And that has made all the difference.", author: "Robert Frost" },
  { quote: "The question isn't who is going to let me; it's who is going to stop me.", author: "Ayn Rand" },
  { quote: "The road to success and the road to failure are almost exactly the same.", author: "Colin R. Davis" },
  { quote: "Develop success from failures. Discouragement and failure are two of the surest stepping stones to success.", author: "Dale Carnegie" },
  { quote: "I've missed more than 9000 shots in my career. I've lost almost 300 games. 26 times I've been trusted to take the game winning shot and missed.", author: "Michael Jordan" },
  { quote: "The successful warrior is the average man, with laser-like focus.", author: "Bruce Lee" },
  { quote: "Don’t let the fear of losing be greater than the excitement of winning.", author: "Robert Kiyosaki" },
  { quote: "If you look at what you have in life, you’ll always have more. If you look at what you don’t have in life, you’ll never have enough.", author: "Oprah Winfrey" },
  { quote: "Life is about making an impact, not making an income.", author: "Kevin Kruse" },
  { quote: "Whatever the mind of man can conceive and believe, it can achieve.", author: "Napoleon Hill" },
  { quote: "The big lesson in life, baby, is never be scared of anyone or anything.", author: "Frank Sinatra" },
  { quote: "Life is like riding a bicycle. To keep your balance, you must keep moving.", author: "Albert Einstein" },
  { quote: "The purpose of life is not to be happy. It is to be useful, to be honorable, to be compassionate.", author: "Ralph Waldo Emerson" },
  { quote: "I’ve learned that people will forget what you said, people will forget what you did, but people will never forget how you made them feel.", author: "Maya Angelou" },
  { quote: "Do not dwell in the past, do not dream of the future, concentrate the mind on the present moment.", author: "Buddha" },
  { quote: "The purpose of our lives is to be happy.", author: "Dalai Lama" },
  { quote: "You must not lose faith in humanity. Humanity is an ocean; if a few drops of the ocean are dirty, the ocean does not become dirty.", author: "Mahatma Gandhi" },
  { quote: "The best way out is always through.", author: "Robert Frost" },
  { quote: "What we think, we become.", author: "Buddha" },
  { quote: "The only way to make sense out of change is to plunge into it, move with it, and join the dance.", author: "Alan Watts" },
  { quote: "You can’t use up creativity. The more you use, the more you have.", author: "Maya Angelou" },
  { quote: "The most difficult thing is the decision to act, the rest is merely tenacity.", author: "Amelia Earhart" },
  { quote: "What you do makes a difference, and you have to decide what kind of difference you want to make.", author: "Jane Goodall" },
  { quote: "The best preparation for tomorrow is doing your best today.", author: "H. Jackson Brown Jr." },
  { quote: "Keep your face to the sunshine and you cannot see a shadow.", author: "Helen Keller" },
  { quote: "The greatest obstacle to discovery is not ignorance—it is the illusion of knowledge.", author: "Daniel J. Boorstin" },
  { quote: "You don’t have to be rich to travel well.", author: "Eugene Fodor" },
  { quote: "The only person you should try to be better than is the person you were yesterday.", author: "Tony Robbins" },
  { quote: "It’s not what you look at that matters, it’s what you see.", author: "Henry David Thoreau" },
  { quote: "The greatest wealth is to live content with little.", author: "Plato" },
  { quote: "You can’t go back and change the beginning, but you can start where you are and change the ending.", author: "C.S. Lewis" },
  { quote: "The only true wisdom is in knowing you know nothing.", author: "Socrates" },
  { quote: "You are never too old to set another goal or to dream a new dream.", author: "C.S. Lewis" },
  { quote: "The only way to do great work is to love what you do.", author: "Steve Jobs" },
  { quote: "Believe you can and you're halfway there.", author: "Theodore Roosevelt" },
  { quote: "It always seems impossible until it's done.", author: "Nelson Mandela" },
  { quote: "The future belongs to those who believe in the beauty of their dreams.", author: "Eleanor Roosevelt" },
  { quote: "The only limit to our realization of tomorrow is our doubts of today.", author: "Franklin D. Roosevelt" },
  { quote: "The best way to predict the future is to create it.", author: "Abraham Lincoln" },
  { quote: "What lies behind us and what lies before us are tiny matters compared to what lies within us.", author: "Ralph Waldo Emerson" },
  { quote: "Success is not final, failure is not fatal: It is the courage to continue that counts.", author: "Winston Churchill" },
  { quote: "You miss 100% of the shots you don’t take.", author: "Wayne Gretzky" },
  { quote: "You must be the change you wish to see in the world.", author: "Mahatma Gandhi" },
  { quote: "It does not matter how slowly you go as long as you do not stop.", author: "Confucius" },
  { quote: "Success usually comes to those who are too busy to be looking for it.", author: "Henry David Thoreau" },
  { quote: "Don’t watch the clock; do what it does. Keep going.", author: "Sam Levenson" },
  { quote: "Hardships often prepare ordinary people for an extraordinary destiny.", author: "C.S. Lewis" },
  { quote: "Dream big and dare to fail.", author: "Norman Vaughan" },
  { quote: "Act as if what you do makes a difference. It does.", author: "William James" },
  { quote: "Success is walking from failure to failure with no loss of enthusiasm.", author: "Winston Churchill" },
  { quote: "Don’t let yesterday take up too much of today.", author: "Will Rogers" },
  { quote: "Either you run the day, or the day runs you.", author: "Jim Rohn" },
  { quote: "The only person you are destined to become is the person you decide to be.", author: "Ralph Waldo Emerson" },
  { quote: "Keep your eyes on the stars, and your feet on the ground.", author: "Theodore Roosevelt" },
  { quote: "Do what you can, with what you have, where you are.", author: "Theodore Roosevelt" },
  { quote: "The greatest glory in living lies not in never falling, but in rising every time we fall.", author: "Nelson Mandela" },
  { quote: "Your time is limited, so don’t waste it living someone else’s life.", author: "Steve Jobs" },
  { quote: "If you can dream it, you can do it.", author: "Walt Disney" },
  { quote: "The journey of a thousand miles begins with one step.", author: "Lao Tzu" },
  { quote: "It’s not whether you get knocked down, it’s whether you get up.", author: "Vince Lombardi" },
  { quote: "You don’t have to be great to start, but you have to start to be great.", author: "Zig Ziglar" },
  { quote: "Strive not to be a success, but rather to be of value.", author: "Albert Einstein" },
  { quote: "I am not a product of my circumstances. I am a product of my decisions.", author: "Stephen Covey" },
  { quote: "When everything seems to be going against you, remember that the airplane takes off against the wind, not with it.", author: "Henry Ford" },
  { quote: "The harder the conflict, the more glorious the triumph.", author: "Thomas Paine" },
  { quote: "We may encounter many defeats but we must not be defeated.", author: "Maya Angelou" },
  { quote: "Opportunities don't happen. You create them.", author: "Chris Grosser" },
  { quote: "Don’t be afraid to give up the good to go for the great.", author: "John D. Rockefeller" },
  { quote: "I find that the harder I work, the more luck I seem to have.", author: "Thomas Jefferson" },
  { quote: "The secret of getting ahead is getting started.", author: "Mark Twain" },
  { quote: "Life is 10% what happens to you and 90% how you react to it.", author: "Charles R. Swindoll" },
  { quote: "The mind is everything. What you think you become.", author: "Buddha" },
  { quote: "Whether you think you can or you think you can’t, you’re right.", author: "Henry Ford" },
  { quote: "Don’t wait. The time will never be just right.", author: "Napoleon Hill" },
  { quote: "Everything you’ve ever wanted is on the other side of fear.", author: "George Addair" },
  { quote: "Challenges are what make life interesting and overcoming them is what makes life meaningful.", author: "Joshua J. Marine" },
  { quote: "The way to get started is to quit talking and begin doing.", author: "Walt Disney" },
  { quote: "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.", author: "Christian D. Larson" },
  { quote: "Your life does not get better by chance, it gets better by change.", author: "Jim Rohn" },
  { quote: "The only place where success comes before work is in the dictionary.", author: "Vidal Sassoon" },
  { quote: "You don’t need to see the whole staircase, just take the first step.", author: "Martin Luther King Jr." },
  { quote: "Dreams don’t work unless you do.", author: "John C. Maxwell" },
  { quote: "Go the extra mile. It’s never crowded there.", author: "Dr. Wayne D. Dyer" },
  { quote: "Keep your face always toward the sunshine, and shadows will fall behind you.", author: "Walt Whitman" },
  { quote: "Make each day your masterpiece.", author: "John Wooden" },
  { quote: "Wherever you go, go with all your heart.", author: "Confucius" },
  { quote: "Turn your wounds into wisdom.", author: "Oprah Winfrey" },
  { quote: "We generate fears while we sit. We overcome them by action.", author: "Dr. Henry Link" },
  { quote: "The best revenge is massive success.", author: "Frank Sinatra" },
  { quote: "You don’t find the happy life. You make it.", author: "Camilla Eyring Kimball" },
  { quote: "Inspiration does exist, but it must find you working.", author: "Pablo Picasso" },
  { quote: "Show up, show up, show up, and after a while the muse shows up, too.", author: "Isabel Allende" },
  { quote: "Don’t count the days, make the days count.", author: "Muhammad Ali" },
  { quote: "Nothing is impossible. The word itself says ‘I’m possible!’", author: "Audrey Hepburn" },
  { quote: "Always do your best. What you plant now, you will harvest later.", author: "Og Mandino" },
  { quote: "You get what you give.", author: "Jennifer Lopez" },
  { quote: "Happiness is not something ready-made. It comes from your own actions.", author: "Dalai Lama" },
  { quote: "The only way to achieve the impossible is to believe it is possible.", author: "Charles Kingsleigh" },
  { quote: "The best time to plant a tree was 20 years ago. The second best time is now.", author: "Chinese Proverb" },
  { quote: "You are enough just as you are.", author: "Meghan Markle" },
  { quote: "Do what you love, and the money will follow.", author: "Marsha Sinetar" },
  { quote: "The power of imagination makes us infinite.", author: "John Muir" },
  { quote: "You are braver than you believe, stronger than you seem, and smarter than you think.", author: "A.A. Milne" },
  { quote: "Success is getting what you want, happiness is wanting what you get.", author: "W.P. Kinsella" },
  { quote: "Stay close to anything that makes you glad you are alive.", author: "Hafiz" },
  { quote: "You do not find the happy life. You make it.", author: "Thomas S. Monson" },
  { quote: "The most wasted of days is one without laughter.", author: "E.E. Cummings" },
  { quote: "Make your life a masterpiece; imagine no limitations on what you can be, have, or do.", author: "Brian Tracy" },
  { quote: "You are never too old to reinvent yourself.", author: "Steve Harvey" },
  { quote: "The only thing standing between you and your goal is the story you keep telling yourself.", author: "Jordan Belfort" },
  { quote: "Every moment is a fresh beginning.", author: "T.S. Eliot" },
  { quote: "Change your thoughts and you change your world.", author: "Norman Vincent Peale" },
  { quote: "The greatest gift you can give someone is your time.", author: "Rick Warren" },
  { quote: "You don’t need to be better than anyone else, you just need to be better than you used to be.", author: "Wayne Dyer" },
  { quote: "Live as if you were to die tomorrow. Learn as if you were to live forever.", author: "Mahatma Gandhi" },
  { quote: "Do not wait to strike till the iron is hot, but make it hot by striking.", author: "William Butler Yeats" } // Unique quote from new list
];

function App() {
  const [quote, setQuote] = useState(quotes[Math.floor(Math.random() * quotes.length)]);

  const fetchQuote = () => {
    const randomQuote = quotes[Math.floor(Math.random() * quotes.length)];
    setQuote(randomQuote);
  };

  return (
    <>
      <div className="bubble"></div>
      <div className="bubble"></div>
      <div className="bubble"></div>
      <div className="bubble"></div>
      <div className="bubble"></div>

      <div className="container">
        <div className="quote-box">
          <p className="quote">{quote.quote}</p>
          <p className="author">— {quote.author}</p>
          <button className="new-quote-btn" onClick={fetchQuote}>New Quote</button>
        </div>
      </div>
    </>
  );
}

export default App;